### ISSUE TITLE
How to install project

### ISSUE THREAD

**Issue by kingleroyg** [yoeran/nw-template#1]
I tried the following process but I got the following error:
`npm ERR! missing script: start`

process:

- Git clone project
- cd into nw-template
- npm install
- npm install -g nw
- npm start

**Comment by yoeran** [comment]
You can start the project with `gulp debug` instead of `npm start`. When you want to make a build out of your application use `gulp dist`.

Also just running `gulp` in the root of the folder will give you a kind of manual.
